# Generated by Django 4.2.30 on 2026-08-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('roster', '0009_staff_scheduling_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockingPatternImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('period_label', models.CharField(blank=True, max_length=120)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeClockingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weeks_observed', models.PositiveSmallIntegerField(default=0)),
                ('active_weeks', models.PositiveSmallIntegerField(default=0)),
                ('average_weekly_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('average_shifts_per_active_week', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('typical_start_time', models.TimeField(blank=True, null=True)),
                ('typical_end_time', models.TimeField(blank=True, null=True)),
                ('weekday_counts', models.JSONField(blank=True, default=dict)),
                ('worker_type', models.CharField(choices=[('core', 'Core'), ('regular_part_time', 'Regular part-time'), ('occasional', 'Occasional'), ('insufficient', 'Insufficient history')], default='insufficient', max_length=30)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clocking_pattern', to='employees.employee')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_patterns', to='roster.clockingpatternimport')),
            ],
            options={
                'ordering': ['employee__first_name', 'employee__last_name'],
            },
        ),
    ]
