# Generated by Django 4.2.30 on 2026-08-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_clockingpatternimport_employeeclockingpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftresponse',
            name='wants_replacement_shift',
            field=models.BooleanField(default=False, help_text='Employee cannot work this shift but would like replacement hours.'),
        ),
    ]
