# Generated by Django 4.2.30 on 2026-08-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('roster', '0011_shiftresponse_wants_replacement_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRosterNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=250)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_notices', to='employees.employee')),
                ('roster_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notices', to='roster.rosterweek')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
