# Generated by Django 4.2.30 on 2026-08-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_staffrosternotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterweek',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Use this roster as the normal weekly starting template.'),
        ),
    ]
