# Generated by Django 4.2.30 on 2026-09-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_can_work_kitchen_employee_can_work_washup_and_more'),
        ('roster', '0013_rosterweek_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveragepattern',
            name='department',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('washup', 'Wash up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dailystaffingpattern',
            name='department',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('washup', 'Wash up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeepattern',
            name='normal_department',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('washup', 'Wash up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeescheduleprofile',
            name='preferred_department',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('washup', 'Wash up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='openshift',
            name='department',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('washup', 'Wash up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shift',
            name='department',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('washup', 'Wash up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='shifttemplatepattern',
            name='department',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('washup', 'Wash up')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffingpattern',
            name='department',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('washup', 'Wash up')], max_length=20),
        ),
        migrations.CreateModel(
            name='UnresolvedShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('department', models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('washup', 'Wash up')], max_length=20)),
                ('suggested_start_time', models.TimeField(blank=True, null=True)),
                ('suggested_end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unresolved_roster_shifts', to='employees.employee')),
                ('roster_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unresolved_shifts', to='roster.rosterweek')),
            ],
            options={
                'ordering': ['date', 'employee__first_name', 'employee__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='unresolvedshift',
            constraint=models.UniqueConstraint(fields=('roster_week', 'employee', 'date', 'department'), name='unique_unresolved_roster_shift'),
        ),
    ]
