# Generated by Django 4.2.30 on 2026-09-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_work_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_work_washup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('bar', 'Bar'), ('kitchen', 'Kitchen'), ('washup', 'Wash up')], default='restaurant', max_length=20),
        ),
    ]
